"""
    This module defines the 'SubtitleToSpeech' class, which converts subtitle files to speech audio files.
    It supports multiple Text-to-Speech (TTS) services including Harpo, Balabolka, Edge, and ElevenLabs.

    * Usage:
        To use this module, create an instance of the 'SubtitleToSpeech' class and call the 'generate_audio' method.

    * Example usage:
        from subtitle_to_speech import SubtitleToSpeech

        # Create an instance of SubtitleToSpeech
        converter = SubtitleToSpeech(filename="example.srt")

        # Generate audio
        converter.generate_audio(settings)

    * Example usage:
        if __name__ == '__main__':
            converter = SubtitleToSpeech(filename="example.srt")
            converter.generate_audio(settings)

    * Example usage:
        if __name__ == '__main__':
            if 'TTS - *Głos* - ElevenLans' in settings.tts:
                audio_generator = SubtitleToSpeech(filename="")
                audio_generator.srt_to_eac3_elevenlabs() # For Alt Subs
"""

from dataclasses import dataclass
from msvcrt import getch
from os import listdir, path, remove
from subprocess import call, Popen
from threading import Thread
from time import sleep
import sys
import wave


from typing import Dict, List, Optional

import pyttsx3
import pysrt
from edge_tts import Communicate
from pydub import AudioSegment
from pydub.utils import mediainfo

from constants import (WORKING_SPACE,
                       WORKING_SPACE_OUTPUT,
                       WORKING_SPACE_TEMP,
                       WORKING_SPACE_TEMP_MAIN_SUBS,
                       WORKING_SPACE_TEMP_ALT_SUBS,
                       BALABOLKA_PATH,
                       FFMPEG_PATH,
                       console)
from data.settings import Settings

from asyncio import create_task, gather, run, Semaphore, sleep as asyncio_sleep, TimeoutError
from async_timeout import timeout as timeout_scope
from natsort import natsorted
from os import path, stat, listdir, remove

if sys.platform == "win32":
    import asyncio
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())


@dataclass(slots=True)
class SubtitleToSpeech:
    """
        This class provides methods to convert subtitle files to speech audio files.

        Attributes:
            - filename (str): The name of the subtitle file to convert.
            - working_space (str): The path to the working directory.
            - working_space_output (str): The path to the output directory.
            - working_space_temp (str): The path to the temporary directory.
            - working_space_temp_main_subs (str): The path to the main subtitles directory.
            - working_space_temp_alt_subs (str): The path to the alternative subtitles directory.
            - balabolka_path (str): The path to the Balabolka executable.
            - ffmpeg_path (str): The path to the FFmpeg executable.

        Methods:
            - ansi_srt(self) -> None:
                Converts the encoding of the subtitle file to ANSI.

            - srt_to_wav_harpo(self, tts_speed: str, tts_volume: str) -> None:
                Converts the subtitle file to a WAV audio file using Harpo TTS.

            - srt_to_wav_balabolka(self, tts_speed: str, tts_volume: str) -> None:
                Converts the subtitle file to a WAV audio file using Balabolka TTS.

            - srt_to_wav_edge_online(self, tts: str, tts_speed: str, tts_volume: str) -> None:
                Converts the subtitle file to a WAV audio file using Edge TTS.

            - merge_tts_audio(self) -> None:
                Merges the generated TTS audio files.

            - generate_audio(self, settings: Settings) -> None:
                Generates the audio file from the subtitle file using the specified TTS settings.

            - srt_to_eac3_elevenlabs(self) -> None:
                Opens the main_subs folder for the user to add audio files generated by ElevenLabs.
    """

    filename: str
    working_space: str = WORKING_SPACE
    working_space_output: str = WORKING_SPACE_OUTPUT
    working_space_temp: str = WORKING_SPACE_TEMP
    working_space_temp_main_subs: str = WORKING_SPACE_TEMP_MAIN_SUBS
    working_space_temp_alt_subs: str = WORKING_SPACE_TEMP_ALT_SUBS
    balabolka_path: str = BALABOLKA_PATH
    ffmpeg_path: str = FFMPEG_PATH
    _pp_speed: float = 1.0

    def ansi_srt(self) -> None:
        """
            Converts the encoding of the subtitle file to ANSI.

            Raises:
                - UnicodeDecodeError: If the file is not in UTF-8 encoding.
        """
        try:
            with open(path.join(self.working_space_temp_main_subs, self.filename), "r", encoding="utf-8") as source_file:
                content: str = source_file.read()
        except UnicodeDecodeError:
            with open(path.join(self.working_space_temp_main_subs, self.filename), "r", encoding="ANSI") as source_file:
                content: str = source_file.read()

        with open(path.join(self.working_space_temp_main_subs, self.filename), "w", encoding="ANSI", errors="ignore") as target_file:
            target_file.write(content)

        console.print("Zamieniono kodowanie na ANSI:",
                      style='green_bold', end=' ')
        console.print(self.filename)

    def srt_to_wav_harpo(self, tts_speed: str, tts_volume: str) -> None:
        """
            Converts the subtitle file to a WAV audio file using Harpo TTS.

            Args:
                - tts_speed (str): The speed of the TTS voice.
                - tts_volume (str): The volume of the TTS voice.
        """
        self.ansi_srt()
        engine = self._init_engine(tts_speed, tts_volume)
        subtitles: pysrt.SubRipFile = pysrt.open(path.join(
            self.working_space_temp_main_subs, self.filename), encoding='ANSI')
        output_file: str = path.splitext(path.join(
            self.working_space_temp_main_subs, self.filename))[0] + '.wav'
        self._generate_wav_file(engine, subtitles, output_file)
        remove(path.join(self.working_space_temp, "temp.wav"))

    def _init_engine(self, tts_speed: str, tts_volume: str) -> pyttsx3.Engine:
        """
            Initializes the TTS engine with the specified speed and volume.

            Args:
                - tts_speed (str): The speed of the TTS voice.
                - tts_volume (str): The volume of the TTS voice.

            Returns:
                - pyttsx3.Engine: The initialized TTS engine.
        """
        engine: pyttsx3.Engine = pyttsx3.init()
        voices: List[pyttsx3.Voice] = engine.getProperty('voices')
        for voice in voices:
            if voice.name == 'Vocalizer Expressive Zosia Harpo 22kHz':
                engine.setProperty('voice', voice.id)
        engine.setProperty('rate', int(tts_speed))
        engine.setProperty('volume', float(tts_volume))
        return engine

    def _generate_wav_file(self, engine: pyttsx3.Engine, subtitles: pysrt.SubRipFile, output_file: str) -> None:
        """
            Generates a WAV audio file from the given subtitles using the specified TTS engine.

            Args:
                - engine (pyttsx3.Engine): The TTS engine to use for speech synthesis.
                - subtitles (pysrt.SubRipFile): The subtitles to convert to speech.
                - output_file (str): The path to the output WAV file.
        """
        with wave.open(output_file, 'wb') as wav_file:
            wav_file.setnchannels(1)  # Mono
            wav_file.setsampwidth(2)  # 16-bit
            wav_file.setframerate(22500)  # 22kHz

            for i, subtitle in enumerate(subtitles, start=1):
                print(
                    f"{i}\n{subtitle.start.to_time().strftime('%H:%M:%S.%f')[:-3]} --> {subtitle.end.to_time().strftime('%H:%M:%S.%f')[:-3]}\n{subtitle.text}\n")
                start_time: float = subtitle.start.ordinal / 1000.0
                self._save_subtitle_to_wav(engine, subtitle.text)
                if self._pp_speed != 1.0:
                    self._pp_speed_file(path.join(self.working_space_temp, "temp.wav"))
                self._add_empty_frame_if_needed(wav_file, start_time)
                self._add_subtitle_to_wav(wav_file)

    def _save_subtitle_to_wav(self, engine: pyttsx3.Engine, text: str) -> None:
        """
        Saves a single subtitle to a temporary WAV file.

        Args:
            - engine (pyttsx3.Engine): The TTS engine to use for speech synthesis.
            - text (str): The text of the subtitle to convert to speech.
        """
        engine.save_to_file(text, path.join(
            self.working_space_temp, "temp.wav"))
        engine.runAndWait()

    def _add_empty_frame_if_needed(self, wav_file: wave.Wave_write, start_time: float) -> None:
        """
            Adds an empty frame to the WAV file if the start time of the next subtitle is later than the current time in the audio.

            Args:
                - wav_file (wave.Wave_write): The WAV file to add the empty frame to.
                - start_time (float): The start time of the next subtitle.
        """
        framerate: int = wav_file.getframerate()
        nframes: int = wav_file.getnframes()
        current_time: float = nframes / float(framerate)
        if start_time > current_time:
            empty_frame_duration: int = int(
                (start_time - current_time) * framerate)
            empty_frame: bytes = b'\x00' * empty_frame_duration * 2
            wav_file.writeframes(empty_frame)

    def _add_subtitle_to_wav(self, wav_file: wave.Wave_write) -> None:
        """
            Adds a subtitle to the WAV file.

            Args:
                - wav_file (wave.Wave_write): The WAV file to add the subtitle to.
        """
        with wave.open(path.join(self.working_space_temp, "temp.wav"), 'rb') as temp_file:
            data: bytes = temp_file.readframes(temp_file.getnframes())
            wav_file.writeframes(data)

    def srt_to_wav_balabolka(self, tts_speed: str, tts_volume: str) -> None:
        """
            Converts the subtitle file to a WAV audio file using Balabolka TTS.

            Args:
                - tts_speed (str): The speed of the TTS voice.
                - tts_volume (str): The volume of the TTS voice.
        """
        self.ansi_srt()
        balcon_path: str = self.balabolka_path
        file_path: str = path.join(
            self.working_space_temp_main_subs, self.filename)
        output_wav_path: str = path.join(
            self.working_space_temp_main_subs, path.splitext(self.filename)[0] + ".wav")
        command: List[str] = self._prepare_balabolka_command(
            balcon_path, file_path, output_wav_path, tts_speed, tts_volume)

        command_thread: Thread = Thread(
            target=call, args=(command,))
        command_thread.start()

        subtitles: pysrt.SubRipFile = pysrt.open(file_path, encoding='ANSI')
        for subtitle in subtitles:
            self.process_subtitle(subtitle)

        command_thread.join()

        # Balabolka generates whole WAV at once — per-subtitle speed extraction
        if self._pp_speed != 1.0 and path.isfile(output_wav_path):
            self._pp_speed_whole_wav(output_wav_path, subtitles)

    def _prepare_balabolka_command(self, balcon_path: str, file_path: str, output_wav_path: str, tts_speed: str, tts_volume: str) -> List[str]:
        """
            Prepares the command to run Balabolka TTS.

            Args:
                - balcon_path (str): The path to the Balabolka executable.
                - file_path (str): The path to the subtitle file.
                - output_wav_path (str): The path to the output WAV file.
                - tts_speed (str): The speed of the TTS voice.
                - tts_volume (str): The volume of the TTS voice.

            Returns:
                - List[str]: The prepared command.
        """
        return [
            balcon_path,
            "-fr", "48",
            "-f", file_path,
            "-w", output_wav_path,
            "-n", "IVONA 2 Agnieszka",
            "-s", tts_speed,
            "-v", tts_volume
        ]

    def process_subtitle(self, subtitle: pysrt.SubRipItem) -> None:
        """
            Processes a single subtitle.

            Args:
                - subtitle (pysrt.SubRipItem): The subtitle to process.
        """
        i: int = subtitle.index
        start_time: str = subtitle.start.to_time().strftime('%H:%M:%S.%f')[:-3]
        end_time: str = subtitle.end.to_time().strftime('%H:%M:%S.%f')[:-3]
        text: str = subtitle.text
        print(f"{i}\n{start_time} --> {end_time}\n{text}\n")
        sleep(0.02)

    async def generate_speech(self, subtitle: pysrt.SubRipItem, voice: str, output_file: str, rate: str, volume: str) -> None:
        """
            Generates speech from a single subtitle using the specified TTS voice.

            Args:
                - subtitle (pysrt.SubRipItem): The subtitle to convert to speech.
                - voice (str): The TTS voice to use.
                - output_file (str): The path to the output audio file.
                - rate (str): The speed of the TTS voice.
                - volume (str): The volume of the TTS voice.
        """
        communicate = Communicate(
            subtitle.text, voice, rate=rate, volume=volume)
        with open(output_file, "wb") as file:
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    file.write(chunk["data"])

    async def generate_wav_files(self, subtitles: pysrt.SubRipFile, voice: str, rate: str, volume: str) -> List[str]:
        """
            Generates WAV audio files from the given subtitles using the specified TTS voice.

            Args:
                - subtitles (pysrt.SubRipFile): The subtitles to convert to speech.
                - voice (str): The TTS voice to use.
                - rate (str): The speed of the TTS voice.
                - volume (str): The volume of the TTS voice.

            Returns:
                - List[str]: The paths to the generated WAV files.
        """
        tasks = []
        mp3_files: List[str] = []
        file_name: str = path.splitext(subtitles.path)[0]
        # Zmniejszam liczbę równoległych połączeń
        semaphore: Semaphore = Semaphore(1)
        timeout: float = 30.0  # Dodaję timeout na połączenie

        async def generate_with_retry(subtitle: pysrt.SubRipItem, output_file: str, max_retries: int = 3) -> None:
            async with semaphore:
                for attempt in range(max_retries):
                    try:
                        async with timeout_scope(timeout):
                            await self.generate_speech(subtitle, voice, output_file, rate, volume)
                            if path.exists(output_file) and stat(output_file).st_size > 0:
                                return
                            # Zwiększam czas oczekiwania między próbami
                            await asyncio_sleep(2)
                    except (TimeoutError, Exception) as e:
                        if attempt == max_retries - 1:
                            console.print(
                                f"Failed to generate {output_file} after {max_retries} attempts: {e}", style="red_bold")
                            raise
                        # Zwiększam czas oczekiwania proporcjonalnie do liczby prób
                        await asyncio_sleep(attempt * 2)

        for i, subtitle in enumerate(subtitles, start=1):
            output_file: str = f"{file_name}_{i}.mp3"
            mp3_files.append(output_file)
            tasks.append(create_task(
                generate_with_retry(subtitle, output_file)))

        await gather(*tasks)
        return natsorted(mp3_files)

    def merge_audio_files(self, mp3_files: List[str], subtitles: pysrt.SubRipFile, dir_path: str) -> None:
        """
            Merges the given MP3 audio files into a single WAV file.

            Args:
                - mp3_files (List[str]): The paths to the MP3 files to merge.
                - subtitles (pysrt.SubRipFile): The subtitles corresponding to the audio files.
                - dir_path (str): The directory where the audio files are located.
        """
        file_name: str = path.splitext(subtitles.path)[0]
        with wave.open(f"{file_name}.wav", 'wb') as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(24000)

            for i, mp3_file in enumerate(mp3_files, start=1):
                print(
                    f"{i}\n{subtitles[i-1].start.to_time().strftime('%H:%M:%S.%f')[:-3]} --> {subtitles[i-1].end.to_time().strftime('%H:%M:%S.%f')[:-3]}\n{subtitles[i-1].text}\n")
                mp3_file_path: str = path.join(dir_path, mp3_file)
                if path.isfile(mp3_file_path):
                    start_time: float = subtitles[i-1].start.ordinal / 1000.0
                    sound: AudioSegment = AudioSegment.from_file(
                        mp3_file_path, format="mp3")
                    remove(mp3_file_path)
                    self._add_empty_frame_if_needed(wav_file, start_time)
                    sound_data: bytes = sound.raw_data
                    wav_file.writeframes(sound_data)

    def srt_to_wav_edge_online(self, tts: str, tts_speed: str, tts_volume: str) -> None:
        """
            Converts the subtitle file to a WAV audio file using Edge TTS.

            Args:
                - tts (str): The TTS service to use.
                - tts_speed (str): The speed of the TTS voice.
                - tts_volume (str): The volume of the TTS voice.
        """
        self.ansi_srt()
        voice = "pl-PL-ZofiaNeural" if tts == "TTS - Zofia - Edge" else "pl-PL-MarekNeural"

        subtitles: pysrt.SubRipFile = pysrt.open(path.join(
            self.working_space_temp_main_subs, self.filename), encoding='ANSI')
        mp3_files: List[str] = run(self.generate_wav_files(
            subtitles, voice, tts_speed, tts_volume))
        if self._pp_speed != 1.0:
            for mp3_file in mp3_files:
                mp3_path = path.join(self.working_space_temp_main_subs, path.basename(mp3_file)) if not path.isabs(mp3_file) else mp3_file
                if path.isfile(mp3_path):
                    self._pp_speed_file(mp3_path)
        self.merge_audio_files(mp3_files, subtitles,
                               self.working_space_temp_main_subs)

    def srt_to_wav_stylish(self, tts_speed: str, tts_volume: str) -> None:
        """Converts the subtitle file to a WAV audio file using STylish-TTS-Pl.

        Args:
            tts_speed: Speed multiplier as string (e.g. '1.0'). Range 0.5-2.0.
            tts_volume: Volume (unused, kept for interface consistency).
        """
        from modules.tts_stylish import StylishTTS, STYLISH_SAMPLE_RATE

        self.ansi_srt()
        subtitles: pysrt.SubRipFile = pysrt.open(path.join(
            self.working_space_temp_main_subs, self.filename), encoding='ANSI')
        output_file: str = path.splitext(path.join(
            self.working_space_temp_main_subs, self.filename))[0] + '.wav'

        speed = float(tts_speed) if tts_speed not in ('auto', '') else 1.0
        tts = StylishTTS()

        with wave.open(output_file, 'wb') as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(STYLISH_SAMPLE_RATE)

            for i, subtitle in enumerate(subtitles, start=1):
                print(
                    f"{i}\n{subtitle.start.to_time().strftime('%H:%M:%S.%f')[:-3]} --> "
                    f"{subtitle.end.to_time().strftime('%H:%M:%S.%f')[:-3]}\n{subtitle.text}\n")
                start_time: float = subtitle.start.ordinal / 1000.0

                audio_int16 = tts.synthesize_long(subtitle.text, speed=speed)

                if self._pp_speed != 1.0 and len(audio_int16) > 0:
                    audio_int16 = self._pp_speed_audio(audio_int16, STYLISH_SAMPLE_RATE)

                framerate: int = wav_file.getframerate()
                nframes: int = wav_file.getnframes()
                current_time: float = nframes / float(framerate)
                if start_time > current_time:
                    empty_frames: int = int((start_time - current_time) * framerate)
                    wav_file.writeframes(b'\x00' * empty_frames * 2)

                if len(audio_int16) > 0:
                    wav_file.writeframes(audio_int16.tobytes())

    def srt_to_wav_fish_api(self, tts_speed: str, tts_volume: str, fish_voice: Optional[str] = None, fish_temperature: float = 0.8) -> None:
        """Converts the subtitle file to a WAV audio file using Fish Audio S2 Pro API.

        Args:
            tts_speed: Unused (auto), kept for interface consistency.
            tts_volume: Unused (auto), kept for interface consistency.
            fish_voice: Name of the voice profile to use.
            fish_temperature: Temperature for expressiveness (0.0-1.0).
        """
        from modules.tts_fish_api import FishTTSClient, FISH_SAMPLE_RATE

        self.ansi_srt()
        subtitles: pysrt.SubRipFile = pysrt.open(path.join(
            self.working_space_temp_main_subs, self.filename), encoding='ANSI')
        output_file: str = path.splitext(path.join(
            self.working_space_temp_main_subs, self.filename))[0] + '.wav'

        client = FishTTSClient(voice=fish_voice, temperature=fish_temperature)

        with wave.open(output_file, 'wb') as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(FISH_SAMPLE_RATE)

            for i, subtitle in enumerate(subtitles, start=1):
                print(
                    f"{i}\n{subtitle.start.to_time().strftime('%H:%M:%S.%f')[:-3]} --> "
                    f"{subtitle.end.to_time().strftime('%H:%M:%S.%f')[:-3]}\n{subtitle.text}\n")
                start_time: float = subtitle.start.ordinal / 1000.0

                audio_int16 = client.synthesize(subtitle.text)

                if self._pp_speed != 1.0 and len(audio_int16) > 0:
                    audio_int16 = self._pp_speed_audio(audio_int16, FISH_SAMPLE_RATE)

                framerate: int = wav_file.getframerate()
                nframes: int = wav_file.getnframes()
                current_time: float = nframes / float(framerate)
                if start_time > current_time:
                    empty_frames: int = int((start_time - current_time) * framerate)
                    wav_file.writeframes(b'\x00' * empty_frames * 2)

                if len(audio_int16) > 0:
                    wav_file.writeframes(audio_int16.tobytes())

    def srt_to_wav_readlover(
        self,
        tts_speed: str,
        tts_volume: str,
        readlover_api_key: str,
        readlover_speaker_id: int = 6,
        readlover_preset: str = "neutral",
    ) -> None:
        """Converts the subtitle file to a WAV audio file using ReadLover API.

        Args:
            tts_speed: length_scale value (0.1-4.0).
            tts_volume: Unused (auto), kept for interface consistency.
            readlover_api_key: Bearer API key for ReadLover.
            readlover_speaker_id: Speaker ID from /v1/voices.
            readlover_preset: 'neutral' or 'expressive'.
        """
        from modules.tts_readlover import ReadLoverClient, READLOVER_SAMPLE_RATE

        length_scale = 1.0
        try:
            val = float(tts_speed)
            if 0.1 <= val <= 4.0:
                length_scale = val
        except (ValueError, TypeError):
            pass

        self.ansi_srt()
        subtitles: pysrt.SubRipFile = pysrt.open(path.join(
            self.working_space_temp_main_subs, self.filename), encoding='ANSI')
        output_file: str = path.splitext(path.join(
            self.working_space_temp_main_subs, self.filename))[0] + '.wav'

        client = ReadLoverClient(
            api_key=readlover_api_key,
            speaker_id=readlover_speaker_id,
            preset=readlover_preset,
            length_scale=length_scale,
        )

        with wave.open(output_file, 'wb') as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(READLOVER_SAMPLE_RATE)

            for i, subtitle in enumerate(subtitles, start=1):
                print(
                    f"{i}\n{subtitle.start.to_time().strftime('%H:%M:%S.%f')[:-3]} --> "
                    f"{subtitle.end.to_time().strftime('%H:%M:%S.%f')[:-3]}\n{subtitle.text}\n")
                start_time: float = subtitle.start.ordinal / 1000.0

                audio_int16 = client.synthesize(subtitle.text)

                if self._pp_speed != 1.0 and len(audio_int16) > 0:
                    audio_int16 = self._pp_speed_audio(audio_int16, READLOVER_SAMPLE_RATE)

                framerate: int = wav_file.getframerate()
                nframes: int = wav_file.getnframes()
                current_time: float = nframes / float(framerate)
                if start_time > current_time:
                    empty_frames: int = int((start_time - current_time) * framerate)
                    wav_file.writeframes(b'\x00' * empty_frames * 2)

                if len(audio_int16) > 0:
                    wav_file.writeframes(audio_int16.tobytes())

    def srt_to_wav_elevenbytes(self, tts_speed: str, tts_volume: str, elevenbytes_voice: Optional[str] = None) -> None:
        """Async parallel batch synthesis via ElevenBytes (ElevenLabs proxy).

        Saves each MP3 to disk cache so progress survives crashes.
        On restart, loads existing MP3s and retries only missing ones.

        Args:
            tts_speed: Unused (auto), kept for interface consistency.
            tts_volume: Unused (auto), kept for interface consistency.
            elevenbytes_voice: Voice alias or raw ElevenLabs voice_id.
        """
        import re
        import sys
        import time as _time
        from io import BytesIO
        from pathlib import Path as _Path
        from modules.tts_elevenbytes import TTS as ElevenBytesTTS
        import numpy as np

        # Force unbuffered stdout for real-time terminal visibility
        if hasattr(sys.stdout, 'reconfigure'):
            sys.stdout.reconfigure(line_buffering=True)

        ELEVENBYTES_SAMPLE_RATE: int = 44100
        HARD_TIMEOUT_S: float = 5 * 60 * 60  # 5h absolute limit
        ROUND_COOLDOWN: float = 10.0

        self.ansi_srt()
        subtitles: pysrt.SubRipFile = pysrt.open(path.join(
            self.working_space_temp_main_subs, self.filename), encoding='ANSI')
        output_file: str = path.splitext(path.join(
            self.working_space_temp_main_subs, self.filename))[0] + '.wav'

        # MP3 cache dir — survives crashes
        cache_dir = _Path(self.working_space_temp_main_subs) / "_elevenbytes_cache"
        cache_dir.mkdir(parents=True, exist_ok=True)

        tts = ElevenBytesTTS(default_voice=elevenbytes_voice or 'dallin')

        # ── Phase 1: Parse & clean all subtitles ──
        sub_items: list[tuple[int, float, str]] = []
        for i, subtitle in enumerate(subtitles):
            text: str = subtitle.text.strip()
            text = re.sub(r'\{[^}]*\}', '', text)
            text = re.sub(r'<[^>]+>', '', text)
            text = text.replace('\\N', ' ').replace('\\n', ' ')
            text = re.sub(r'\s+', ' ', text).strip()
            start_time: float = subtitle.start.ordinal / 1000.0
            sub_items.append((i, start_time, text))

        # Print all subtitles like original SRT display
        for i, (idx, st, text) in enumerate(sub_items, start=1):
            sub = subtitles[idx]
            print(
                f"{i}/{len(sub_items)}  "
                f"{sub.start.to_time().strftime('%H:%M:%S.%f')[:-3]} --> "
                f"{sub.end.to_time().strftime('%H:%M:%S.%f')[:-3]}  "
                f"{text[:80]}", flush=True)

        # ── Phase 1.5: Load cached MP3s from previous runs ──
        cached_indices: set[int] = set()
        for mp3_file in cache_dir.glob("*.mp3"):
            try:
                idx = int(mp3_file.stem)
                if mp3_file.stat().st_size >= 1024:
                    cached_indices.add(idx)
            except (ValueError, OSError):
                pass

        synthable: list[tuple[int, str]] = [
            (idx, text) for idx, _, text in sub_items if len(text) >= 2
        ]
        total_to_synth: int = len(synthable)

        if cached_indices:
            console.print(
                f"[cyan bold]ElevenBytes cache: {len(cached_indices)} "
                f"MP3s loaded from previous run"
            )

        pending: list[tuple[int, str]] = [
            (idx, text) for idx, text in synthable if idx not in cached_indices
        ]

        print(
            f"\nElevenBytes: {len(sub_items)} parsed, "
            f"{len(cached_indices)} cached, "
            f"{len(pending)} to synthesize",
            flush=True,
        )

        # ── Phase 2: Parallel with real-time output — retry until 100% or 5h ──
        from concurrent.futures import ThreadPoolExecutor, as_completed
        import threading

        t_start: float = _time.monotonic()
        round_num: int = 0
        done_count: int = len(cached_indices)
        _print_lock = threading.Lock()
        CONCURRENCY: int = 85

        def _synth_one(orig_idx: int, text: str) -> tuple[int, str, bytes | None, str | None, float]:
            """Synthesize single subtitle. Returns (idx, text, audio|None, error|None, elapsed)."""
            t0 = _time.monotonic()
            try:
                mp3 = tts.synthesize_sync(text)
                return (orig_idx, text, mp3, None, _time.monotonic() - t0)
            except Exception as exc:
                return (orig_idx, text, None, str(exc), _time.monotonic() - t0)

        while pending:
            elapsed: float = _time.monotonic() - t_start
            if elapsed >= HARD_TIMEOUT_S:
                console.print(
                    f"[red bold]ElevenBytes: 5h timeout — "
                    f"{done_count}/{total_to_synth} done, "
                    f"{len(pending)} still pending."
                )
                break

            round_num += 1
            remaining_m: float = (HARD_TIMEOUT_S - elapsed) / 60.0

            print(f"\n{'=' * 60}", flush=True)
            print(
                f"ElevenBytes round {round_num} — {len(pending)} requests "
                f"(concurrency={CONCURRENCY}) | done: {done_count}/{total_to_synth} "
                f"| remaining: {remaining_m:.0f}min",
                flush=True,
            )
            print(f"{'=' * 60}", flush=True)

            new_pending: list[tuple[int, str]] = []
            round_ok: int = 0

            with ThreadPoolExecutor(max_workers=CONCURRENCY) as pool:
                future_map = {
                    pool.submit(_synth_one, idx, text): (idx, text)
                    for idx, text in pending
                }
                for future in as_completed(future_map):
                    orig_idx, orig_text, audio, error, elapsed_s = future.result()
                    sub = subtitles[orig_idx]
                    time_range = (
                        f"{sub.start.to_time().strftime('%H:%M:%S.%f')[:-3]} --> "
                        f"{sub.end.to_time().strftime('%H:%M:%S.%f')[:-3]}"
                    )
                    if audio and len(audio) >= 1024:
                        (cache_dir / f"{orig_idx:04d}.mp3").write_bytes(audio)
                        done_count += 1
                        round_ok += 1
                        kb = len(audio) / 1024
                        with _print_lock:
                            print(
                                f"  OK  #{orig_idx + 1:>3}  {time_range}  "
                                f"{kb:.0f}KB  {elapsed_s:.1f}s  "
                                f"[{done_count}/{total_to_synth}]  {orig_text[:50]}",
                                flush=True,
                            )
                    else:
                        new_pending.append((orig_idx, orig_text))
                        with _print_lock:
                            print(
                                f"  FAIL #{orig_idx + 1:>3}  {time_range}  "
                                f"{error or 'too small'}  {orig_text[:50]}",
                                flush=True,
                            )

            print(
                f"\nRound {round_num}: {round_ok}/{len(pending)} OK | "
                f"Total: {done_count}/{total_to_synth}",
                flush=True,
            )

            pending = new_pending
            if pending:
                if round_ok == 0:
                    print(f"API down — cooldown {ROUND_COOLDOWN:.0f}s...", flush=True)
                    _time.sleep(ROUND_COOLDOWN)
                else:
                    print("Immediate next round...", flush=True)

        # ── Phase 3: Build WAV timeline from cache ──
        with wave.open(output_file, 'wb') as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(ELEVENBYTES_SAMPLE_RATE)

            for idx, start_time, text in sub_items:
                framerate: int = wav_file.getframerate()
                nframes: int = wav_file.getnframes()
                current_time: float = nframes / float(framerate)
                if start_time > current_time:
                    empty_frames: int = int((start_time - current_time) * framerate)
                    wav_file.writeframes(b'\x00' * empty_frames * 2)

                mp3_path = cache_dir / f"{idx:04d}.mp3"
                if not mp3_path.exists():
                    continue

                mp3_bytes: bytes = mp3_path.read_bytes()
                audio_seg = AudioSegment.from_mp3(BytesIO(mp3_bytes))
                audio_seg = audio_seg.set_channels(1).set_frame_rate(ELEVENBYTES_SAMPLE_RATE).set_sample_width(2)
                audio_int16 = np.frombuffer(audio_seg.raw_data, dtype=np.int16)

                if self._pp_speed != 1.0 and len(audio_int16) > 0:
                    audio_int16 = self._pp_speed_audio(audio_int16, ELEVENBYTES_SAMPLE_RATE)

                if len(audio_int16) > 0:
                    wav_file.writeframes(audio_int16.tobytes())

        try:
            tts.close_sync()
        except Exception:
            pass

        # Clean up MP3 cache after successful WAV build
        import shutil as _shutil
        _shutil.rmtree(cache_dir, ignore_errors=True)

        # ── Summary ──
        total_elapsed: float = _time.monotonic() - t_start
        failed_count: int = total_to_synth - done_count
        if failed_count:
            console.print(
                f"[yellow bold]ElevenBytes: {failed_count}/{total_to_synth} "
                f"nie udało się (rounds={round_num}, time={total_elapsed / 60:.1f}min)."
            )
        else:
            console.print(
                f"[green bold]ElevenBytes: {done_count}/{total_to_synth} "
                f"— 100%! (rounds={round_num}, time={total_elapsed / 60:.1f}min)"
            )

    def _pp_speed_file(self, file_path: str) -> None:
        """Applies atempo to a single audio file in-place. No-op if _pp_speed is 1.0."""
        if self._pp_speed == 1.0 or not path.isfile(file_path):
            return
        base, ext = path.splitext(file_path)
        tmp = base + '_pp_tmp' + ext
        filters = ",".join(self._build_atempo_chain(self._pp_speed))
        call([
            self.ffmpeg_path, "-y", "-loglevel", "quiet",
            "-i", file_path, "-af", filters, tmp,
        ])
        if path.isfile(tmp):
            remove(file_path)
            from os import rename
            rename(tmp, file_path)

    def _pp_speed_audio(self, audio_int16, sample_rate: int):
        """Applies atempo to a numpy int16 audio array via FFmpeg temp file."""
        import numpy as np
        tmp_in = path.join(self.working_space_temp, "pp_speed_in.wav")
        tmp_out = path.join(self.working_space_temp, "pp_speed_out.wav")
        with wave.open(tmp_in, 'wb') as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(sample_rate)
            wf.writeframes(audio_int16.tobytes())
        filters = ",".join(self._build_atempo_chain(self._pp_speed))
        call([
            self.ffmpeg_path, "-y", "-loglevel", "quiet",
            "-i", tmp_in, "-af", filters,
            "-c:a", "pcm_s16le", tmp_out,
        ])
        if path.isfile(tmp_out):
            with wave.open(tmp_out, 'rb') as rf:
                result = np.frombuffer(rf.readframes(rf.getnframes()), dtype=np.int16)
            remove(tmp_out)
        else:
            result = audio_int16
        if path.isfile(tmp_in):
            remove(tmp_in)
        return result

    def _pp_speed_whole_wav(self, wav_path: str, subtitles: pysrt.SubRipFile) -> None:
        """Per-subtitle atempo for engines that generate the whole WAV at once (e.g. Balabolka)."""
        with wave.open(wav_path, 'rb') as wf:
            nchannels = wf.getnchannels()
            sampwidth = wf.getsampwidth()
            framerate = wf.getframerate()
            all_frames = wf.readframes(wf.getnframes())

        bps = sampwidth * nchannels
        bytes_per_sec = framerate * bps
        total_bytes = len(all_frames)
        total_ms = (total_bytes / bps / framerate) * 1000.0
        atempo_filters = ",".join(self._build_atempo_chain(self._pp_speed))

        clips: List[tuple] = []
        for i, subtitle in enumerate(subtitles):
            start_ms = subtitle.start.ordinal
            end_ms = subtitles[i + 1].start.ordinal if i + 1 < len(subtitles) else int(total_ms)

            sb = int(start_ms / 1000.0 * bytes_per_sec)
            eb = min(int(end_ms / 1000.0 * bytes_per_sec), total_bytes)
            sb -= sb % bps
            eb -= eb % bps
            if sb >= eb:
                continue

            tmp_in = path.join(self.working_space_temp, "bal_pp_in.wav")
            tmp_out = path.join(self.working_space_temp, "bal_pp_out.wav")
            with wave.open(tmp_in, 'wb') as cf:
                cf.setnchannels(nchannels)
                cf.setsampwidth(sampwidth)
                cf.setframerate(framerate)
                cf.writeframes(all_frames[sb:eb])

            call([
                self.ffmpeg_path, "-y", "-loglevel", "quiet",
                "-i", tmp_in, "-af", atempo_filters,
                "-c:a", "pcm_s16le", tmp_out,
            ])

            if path.isfile(tmp_out):
                with wave.open(tmp_out, 'rb') as sf:
                    clips.append((start_ms, sf.readframes(sf.getnframes())))
                remove(tmp_out)
            if path.isfile(tmp_in):
                remove(tmp_in)

        with wave.open(wav_path, 'wb') as wf:
            wf.setnchannels(nchannels)
            wf.setsampwidth(sampwidth)
            wf.setframerate(framerate)
            for start_ms, clip_bytes in clips:
                cur = wf.getnframes() / float(framerate)
                gap = start_ms / 1000.0 - cur
                if gap > 0:
                    wf.writeframes(b'\x00' * int(gap * framerate) * bps)
                wf.writeframes(clip_bytes)

    @staticmethod
    def _build_atempo_chain(speed: float) -> List[str]:
        """Builds a chain of atempo filters for FFmpeg.

        The atempo filter accepts values in [0.5, 100.0]. For speeds outside
        the comfortable 0.5-2.0 range, we chain multiple filters.

        Args:
            speed: Desired speed multiplier (0.5-100.0).

        Returns:
            List of atempo filter strings to chain.
        """
        filters: List[str] = []
        remaining = max(0.5, min(speed, 100.0))
        while remaining > 2.0:
            filters.append("atempo=2.0")
            remaining /= 2.0
        while remaining < 0.5:
            filters.append("atempo=0.5")
            remaining /= 0.5
        filters.append(f"atempo={remaining:.4f}")
        return filters

    def _ffmpeg_post_process(
        self, input_path: str, output_path: str,
        tts_speed: str, tts_volume: str,
    ) -> None:
        """Applies speed and volume adjustment via FFmpeg without pitch change.

        Args:
            input_path: Path to the raw WAV file.
            output_path: Path for the processed WAV file.
            tts_speed: Speed multiplier as string (e.g. '1.0').
            tts_volume: Volume adjustment in dB as string (e.g. '0', '7').
        """
        speed = float(tts_speed) if tts_speed not in ('auto', '') else 1.0
        volume_db = float(tts_volume) if tts_volume not in ('auto', '', '0') else 0.0

        filters: List[str] = []

        if speed != 1.0:
            filters.extend(self._build_atempo_chain(speed))

        if volume_db != 0.0:
            filters.append(f"volume={volume_db:.1f}dB")

        if not filters:
            # No processing needed — just rename
            from shutil import move
            move(input_path, output_path)
            return

        filter_str = ",".join(filters)
        command: List[str] = [
            self.ffmpeg_path,
            "-y",
            "-i", input_path,
            "-af", filter_str,
            "-c:a", "pcm_s16le",
            output_path,
        ]
        console.print(
            f"FFmpeg post-processing: speed={speed}, volume={volume_db}dB",
            style='blue_bold',
        )
        call(command)

    def merge_tts_audio(self) -> None:
        """
        Merges the generated TTS audio files.
        """
        main_subs_files_dict: Dict[str, str] = self._get_files_dict(
            self.working_space_temp_main_subs)
        tmp_files_dict: Dict[str, str] = self._get_files_dict(
            self.working_space_temp)

        for file_name, main_subs_file in main_subs_files_dict.items():
            main_subs_file_path: str = path.join(
                self.working_space_temp_main_subs, main_subs_file)
            output_file: str = path.join(
                self.working_space_output, file_name + ".eac3")

            if file_name in tmp_files_dict:
                tmp_file: str = tmp_files_dict[file_name]
                tmp_file_path: str = path.join(
                    self.working_space_temp, tmp_file)

                main_subs_file_duration: float = self._get_file_duration(
                    main_subs_file_path)
                tmp_file_duration: float = self._get_file_duration(
                    tmp_file_path)

                input_file_1: str
                input_file_2: str
                if main_subs_file_duration > tmp_file_duration:
                    input_file_1, input_file_2 = main_subs_file_path, tmp_file_path
                else:
                    input_file_1, input_file_2 = tmp_file_path, main_subs_file_path

                self._merge_files(input_file_1, input_file_2, output_file)

                remove(main_subs_file_path)
                remove(tmp_file_path)
            else:
                self._convert_to_eac3(main_subs_file_path, output_file)
                remove(main_subs_file_path)
            self._remove_same_name_files(
                self.working_space_temp_main_subs, file_name)

    def _get_files_dict(self, directory: str) -> Dict[str, str]:
        """
            Gets a dictionary of the files in the given directory, excluding files with certain extensions.

            Args:
                - directory (str): The directory to get the files from.

            Returns:
                - Dict[str, str]: A dictionary of the files in the directory.
        """
        excluded_extensions: List[str] = ["srt", "ass"]
        return {path.splitext(f)[0]: f for f in listdir(directory) if path.splitext(f)[1][1:].lower() not in excluded_extensions}

    def _get_file_duration(self, file_path: str) -> float:
        """
            Gets the duration of the file at the given path.

            Args:
                - file_path (str): The path to the file.

            Returns:
                - float: The duration of the file in seconds.
        """
        return float(mediainfo(file_path)['duration'])

    def _merge_files(self, input_file_1: str, input_file_2: str, output_file: str):
        """
            Merges two audio files into a single file.

            Args:
                - input_file_1 (str): The path to the first input file.
                - input_file_2 (str): The path to the second input file.
                - output_file (str): The path to the output file.
        """
        if 'main_subs' in input_file_1:
            command: List[str] = [
                self.ffmpeg_path,
                "-i", input_file_1,
                "-i", input_file_2,
                "-filter_complex", "[0:a]volume=7dB[a1];[a1][1:a]amix=inputs=2:duration=longest",
                "-c:a", "eac3",
                output_file
            ]
        else:
            command: List[str] = [
                self.ffmpeg_path,
                "-i", input_file_1,
                "-i", input_file_2,
                "-filter_complex", "[1:a]volume=7dB[a1];[0:a][a1]amix=inputs=2:duration=longest",
                "-c:a", "eac3",
                output_file
            ]
        call(command)

# Dla ELEVENLABS
        # if 'main_subs' in input_file_1:
        #     command: List[str] = [
        #         self.ffmpeg_path,
        #         "-i", input_file_1,
        #         "-i", input_file_2,
        #         "-filter_complex", "[0:a]volume=14dB[a1];[a1][1:a]amix=inputs=2:duration=longest",
        #         output_file
        #     ]
        # else:
        #     command: List[str] = [
        #         self.ffmpeg_path,
        #         "-i", input_file_1,
        #         "-i", input_file_2,
        #         "-filter_complex", "[1:a]volume=14dB[a1];[0:a][a1]amix=inputs=2:duration=longest",
        #         output_file
        #     ]
        # call(command)

    def _convert_to_eac3(self, input_file: str, output_file: str):
        """
            Converts an audio file to EAC3 format.

            Args:
                - input_file (str): The path to the input file.
                - output_file (str): The path to the output file.
        """
        command: List[str] = [
            self.ffmpeg_path,
            "-i", input_file,
            "-c:a", "eac3",
            output_file
        ]
        call(command)

    def _remove_same_name_files(self, directory: str, file_name: str):
        """
            Removes files with the same name as the given file name from the specified directory.

            Args:
                - directory (str): The directory to remove the files from.
                - file_name (str): The name of the files to remove.
        """
        for file in listdir(directory):
            full = path.join(directory, file)
            if path.isfile(full) and path.splitext(file)[0] == file_name:
                remove(full)

    def generate_audio(self, settings: Settings):
        """
            Generates the audio file from the subtitle file using the specified TTS settings.

            Args:
                - settings (Settings): The TTS settings to use.
        """
        tts: Optional[str] = settings.tts
        tts_speed: Optional[str] = settings.tts_speed
        tts_volume: Optional[str] = settings.tts_volume
        self._pp_speed = float(getattr(settings, 'pp_speed', None) or '1.0')

        if self._pp_speed != 1.0:
            console.print(
                f"Post-processing: atempo={self._pp_speed} (per subtitle)",
                style='blue_bold',
            )

        console.print("Rozpoczynam generowanie pliku audio...",
                      style='green_bold', end=' ')
        console.print(self.filename, style='white_bold')
        if tts == "TTS - Zosia - Harpo":
            self.srt_to_wav_harpo(tts_speed, tts_volume)
        elif tts == "TTS - Agnieszka - Ivona":
            self.srt_to_wav_balabolka(tts_speed, tts_volume)
        elif tts in ["TTS - Zofia - Edge", "TTS - Marek - Edge"]:
            self.srt_to_wav_edge_online(tts, tts_speed, tts_volume)
        elif tts == "TTS - STylish - PL":
            self.srt_to_wav_stylish(tts_speed, tts_volume)
        elif tts == "TTS - Fish Audio API":
            fish_temp = float(settings.fish_temperature or '0.8')
            self.srt_to_wav_fish_api(tts_speed, tts_volume, fish_voice=settings.fish_voice, fish_temperature=fish_temp)
        elif tts == "TTS - ReadLover API":
            self.srt_to_wav_readlover(
                tts_speed,
                tts_volume,
                readlover_api_key=settings.readlover_api_key or '',
                readlover_speaker_id=int(settings.readlover_speaker_id or '6'),
                readlover_preset=settings.readlover_preset or 'neutral',
            )
        elif tts == "TTS - ElevenBytes":
            self.srt_to_wav_elevenbytes(
                tts_speed,
                tts_volume,
                elevenbytes_voice=settings.elevenbytes_voice,
            )
        console.print(
            "Generowanie pliku audio zakończone.", style='green_bold')

        self._apply_post_processing(settings)
        self.merge_tts_audio()

    def _apply_post_processing(self, settings: Settings) -> None:
        """Applies FFmpeg volume adjustment to the whole generated WAV.

        Speed (atempo) is already applied per subtitle during generation.
        This method only handles volume.
        """
        pp_volume_str = getattr(settings, 'pp_volume', None) or '0'
        volume_db = float(pp_volume_str)

        if volume_db == 0.0:
            return

        wav_path = path.splitext(path.join(
            self.working_space_temp_main_subs, self.filename))[0] + '.wav'

        if not path.isfile(wav_path):
            return

        console.print(
            f"FFmpeg post-processing: volume={volume_db}dB",
            style='blue_bold',
        )
        raw_path = wav_path + '.pre_vol'
        from shutil import move
        move(wav_path, raw_path)
        call([
            self.ffmpeg_path, "-y", "-loglevel", "quiet",
            "-i", raw_path,
            "-af", f"volume={volume_db:.1f}dB",
            "-c:a", "pcm_s16le", wav_path,
        ])
        remove(raw_path)

    def srt_to_eac3_elevenlabs(self) -> None:
        """
            Opens the main_subs folder for the user to add audio files generated by ElevenLabs.
        """
        Popen(['explorer', path.realpath(self.working_space_temp_main_subs)])

        console.print("\nWygeneruj pliki audio z plików .srt za pomocą 11Labs_TTS_Colab,\na następnie dodaj je do folderu main_subs.",
                      style='yellow_bold')
        console.print(
            "11Labs_TTS_Colab: https://github.com/MattyMroz/11Labs_TTS_Colab", style='yellow_bold')
        console.print(
            "\n[green_italic]Naciśnij dowolny klawisz, aby kontynuować...", end=' ')
        getch()
        console.print()
        self.merge_tts_audio()
